-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 15:05:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gamestore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gamestore` ;

-- -----------------------------------------------------
-- Schema gamestore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamestore` DEFAULT CHARACTER SET utf8mb3 ;
USE `gamestore` ;

-- -----------------------------------------------------
-- Table `gamestore`.`authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamestore`.`authority` (
  `id_auth` BIGINT NOT NULL AUTO_INCREMENT,
  `authority_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_auth`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gamestore`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamestore`.`product` (
  `id_product` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `price` DOUBLE NOT NULL,
  `amount_available` BIGINT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `producer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gamestore`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamestore`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `fk_auth` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_auth_sql_idx` (`fk_auth` ASC) VISIBLE,
  CONSTRAINT `fk_auth_sql`
    FOREIGN KEY (`fk_auth`)
    REFERENCES `gamestore`.`authority` (`id_auth`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gamestore`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamestore`.`purchase` (
  `fk_user_id` BIGINT NOT NULL,
  `fk_product_id` BIGINT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  INDEX `fk_user_idx` (`fk_user_id` ASC) VISIBLE,
  INDEX `fk_product_idx` (`fk_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product`
    FOREIGN KEY (`fk_product_id`)
    REFERENCES `gamestore`.`product` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`fk_user_id`)
    REFERENCES `gamestore`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gamestore`.`user_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamestore`.`user_detail` (
  `id_user_detail` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  INDEX `user_detail_user_one_to_one` (`id_user_detail` ASC) VISIBLE,
  CONSTRAINT `user_detail_user_one_to_one`
    FOREIGN KEY (`id_user_detail`)
    REFERENCES `gamestore`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
